


--<row>

--<MSRDT>202504041000</MSRDT>
--<MSRRGN_NM>도심권</MSRRGN_NM>
--<MSRSTE_NM>중구</MSRSTE_NM> PK
--<PM10>41</PM10> -
--<PM25>36</PM25>
--<O3>0.041</O3>
--<NO2>0.029</NO2>
--<CO>0.5</CO>
--<SO2>0.004</SO2>
--<IDEX_NM>나쁨</IDEX_NM>
--<IDEX_MVL>116</IDEX_MVL>
--<ARPLT_MAIN>PM-2.5</ARPLT_MAIN>

--</row>

DROP TABLE SeoulDustLiveALL CASCADE CONSTRAINT purge;
CREATE TABLE SeoulDustLiveALL(
	MSRDT DATE NOT NULL,						-- 측정일시 
	MSRRGN_NM VARCHAR2(10 CHAR) NOT NULL,		-- 권역 이름
	MSRSTE_NM VARCHAR2(10 CHAR) PRIMARY KEY,	-- 자치구 
	PM10 NUMBER(3) NOT NULL,					-- 미세먼지 농도
	PM25 NUMBER(3) NOT NULL,					-- 초 미세먼지 농도
	O3 NUMBER(4,3) NOT NULL,					-- 오존 농도
	NO2 NUMBER(4,3) NOT NULL,					-- 이산화질소 농도
	CO NUMBER(2,1) NOT NULL,					-- 일산화탄소 농도
	SO2 NUMBER(4,3) NOT NULL,					-- 아황산가스 농도
	IDEX_NM VARCHAR2(3 CHAR) NOT NULL,			-- 통합대기환경지수 평가 등급
	IDEX_MVL NUMBER(5) NOT NULL, 				-- 	통합대기환경지수 수치 0~500
	ARPLT_MAIN NUMBER(2, 1) NOT NULL			-- 주오염물질
);

DROP TABLE SeoulDustLive CASCADE CONSTRAINT purge;
CREATE TABLE SeoulDustLive(
	SD_DATE DATE NOT NULL,						-- 측정일시 
	SD_MSRRGN_NM VARCHAR2(3 CHAR) NOT NULL,		-- 권역 이름
	SD_MSRSTE_NM VARCHAR2(4 CHAR) NOT NULL,		-- 자치구 
	SD_PM10 NUMBER(3) NOT NULL,					-- 미세먼지 농도
	SD_PM25 NUMBER(3) NOT NULL,					-- 초 미세먼지 농도
	SD_IDEX_NM VARCHAR2(10 CHAR) NOT NULL		-- 통합대기환경지수 평가 등급
);

SELECT * FROM SeoulDustLive;
SELECT SD_MSRRGN_NM, AVG(SD_PM10 + SD_PM25) FROM SeoulDustLive GROUP BY SD_MSRRGN_NM ORDER BY AVG(SD_PM10 + SD_PM25) DESC;
DELETE FROM SeoulDustLive;

CREATE TABLE OWM_WEATHER(
	OW_DATE DATE NOT NULL,
	OW_DESC VARCHAR2(20 CHAR) NOT NULL,
	OW_TEMP NUMBER(4,2) NOT NULL,
	OW_FEELS_LIKE NUMBER(4,2) NOT NULL,
	OW_HUMIDITY NUMBER(2) NOT NULL
);
SELECT * FROM OWM_WEATHER;


--# 권역별 미세 + 초미세의 평균
--# 수치가 높은 순서대로 정렬
