



CREATE TABLE APR07_BMI(
	NAME VARCHAR2(3 CHAR) NOT NULL,
	HEIGHT NUMBER(5, 2) NOT NULL,
	WEIGHT NUMBER(5, 2) NOT NULL,
	BMI NUMBER(4, 2) NOT NULL,
	RESULT VARCHAR2(10 CHAR) NOT NULL
);

SELECT * FROM APR07_BMI;

-----------------------------------------
-- 마트
-- 농심, 종로에, 홍길동, 직원 100명
-- 과자
-- 새우깡, 20250505 기한, 4000원, 300g

-- 회사 폐업해도 마트에 들어와있는 과자가 없어지지는 않을 것.


CREATE TABLE APR07_COMPANY(
	C_NAME VARCHAR2(10 CHAR) PRIMARY KEY,
	C_ADDR VARCHAR2(5 CHAR) NOT NULL,
	C_CEO VARCHAR2(10 CHAR) NOT NULL,
	C_EMP NUMBER(3) NOT NULL
);

SELECT * FROM APR07_COMPANY;
INSERT INTO APR07_COMPANY VALUES('농심', '종로', '홍길동', 100);

CREATE SEQUENCE APR07_SNACK_SEQ;
-- SEQ.nextval
CREATE TABLE APR07_SNACK(
	S_NO NUMBER(3) PRIMARY KEY,
	S_NAME VARCHAR2(10 CHAR) NOT NULL,
	S_EXP DATE NOT NULL,
	S_PRICE NUMBER(5) NOT NULL,
	S_WEIGHT NUMBER(4) NOT NULL,
	S_C_NAME VARCHAR2(10 CHAR) NOT NULL
);

SELECT * FROM APR07_SNACK;
INSERT INTO APR07_SNACK VALUES(APR07_SNACK_SEQ.nextval, '새우깡', to_date('20250505', 'YYYYMMDD'), 4000, 300, '농심');

-- 한 페이지당 3개 씩 나오게 할 때,
-- 총 페이지 수?

SELECT * FROM (
	SELECT rownum AS RN, S_NAME, S_EXP, S_PRICE, S_WEIGHT, S_C_NAME FROM (
		SELECT S_NAME, S_EXP, S_PRICE, S_WEIGHT, S_C_NAME
		FROM APR07_SNACK
		ORDER BY S_NAME, S_PRICE
	)
) WHERE RN >= 1 AND RN <= 3;

-- 1*2 + -1 ~~  1*2 + -1 +2 - NOWPAGE = 1 2 3
-- 2*2 + 0- NOWPAGE = 4 5 6
-- 3*2 + 1 - NOWPAGE - 7 8 9
-- 4*2 + 2 - NOWPAGE - 10 11 12
-- 5*2 + 3 NOWPAGE 13 14 15


-- Oracle 12c 버전 이상 
SELECT rownum, m_no, m_name, m_price FROM (
	SELECT m_no, m_name, m_price
	FROM Menu
	ORDER BY m_price DESC
) OFFSET 2 ROWS FETCH NEXT 3 ROWS ONLY;
-- OFFSET 2 ROWS : 앞에서부터 2개의 행은 건너뛰기 -> 3부터 시작
-- FETCH NEXT 3 ROWS ONLY : 그 다음 3개의 행(3, 4, 5)만 가져와라 



